import Head from 'next/head'

import { MyObject } from 'types'

export default function Home() {
  const obj: MyObject = {
    a: "test",
    b: 1
  }
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <code>{JSON.stringify(obj)}</code>
    </>
  )
}
